### ISSUE TITLE
AttributeError running heat_pump_and_chiller.py

### ISSUE THREAD

**Issue by MaGering** [greco-project/pvcompare#138]
I get an AttributeError when I run heat_pump_and_chiller.py separately (not from main.py) both on Linux and Mac OSX:

```
Traceback (most recent call last):
  File "/Volumes/MARIE_RLI/Repositories/pvcompare/pvcompare/heat_pump_and_chiller.py", line 299, in <module>
    weather=weather, mode="heat_pump", lat=52.52437, lon=13.41053
  File "/Volumes/MARIE_RLI/Repositories/pvcompare/pvcompare/heat_pump_and_chiller.py", line 88, in calculate_cops_and_eers
    year = weather.index[int(len(weather) / 2)].year
AttributeError: 'str' object has no attribute 'year'
```

**Comment by MaGering** [comment]
Fixed with PR https://github.com/greco-project/pvcompare/pull/140
